import Head from 'next/head';
import styled from 'styled-components';
import Header from '../components/Header';
import SectionA from '../components/Homepage/SectionA';
import SectionB from '../components/Homepage/SectionB';
import SectionC from '../components/Homepage/SectionC';
import SectionD from '../components/Homepage/SectionD';

export default function HomeComponent() {
  return (
    <div>
      <Head>
        <title>Piset Heang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home>
        <Header />
        <SectionA />
      </Home>
      <SectionB />
      <SectionC />
      <SectionD />
    </div>
  )
}

const Home = styled.div`
  min-height: 1000px;
  background: url(assets/background1.svg) no-repeat center center; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
`